apiVersion: v1
kind: Pod
metadata:
  name: meghdo-agent
  namespace: jenkins
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  serviceAccountName: jenkins
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000
  volumes:
    - name: docker-sock
      persistentVolumeClaim:
        claimName: "jenkins-agents"
    - name: workspace-volume
      emptyDir: {}
    - name: trivy-cache
      emptyDir: {}
    - name: go-cache
      emptyDir: {}
    - name: go-modcache
      emptyDir: {}
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      imagePullPolicy: Always
      args: ["-url", "http://jenkins.jenkins.svc.cluster.local:8080", "-workDir", "/home/jenkins/agent"]
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: docker-sock
          mountPath: "/var/run/docker.sock"
      env:
        - name: JENKINS_URL
          value: "http://jenkins.jenkins.svc.cluster.local:8080"
        - name: JENKINS_TUNNEL
          value: "jenkins-agent.jenkins:50000"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command: ["sleep"]
      args: ["9999999"]
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: docker-sock
          mountPath: "/var/run/docker.sock"
    - name: golang
      image: golang:1.21-alpine
      command:
      - cat
      tty: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      env:
      - name: GOCACHE
        value: "/go-cache"
      - name: GOMODCACHE
        value: "/go-modcache"
      - name: GO111MODULE
        value: "on"
      volumeMounts:
      - name: go-cache
        mountPath: /go-cache
      - name: go-modcache
        mountPath: /go-modcache
      - name: workspace-volume
        mountPath: /home/jenkins/agent
    - name: infra-tools
      image: meghdo/infra-tools:v1.0
      command: ["sleep"]
      args: ["9999999"]
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
    - name: trivy
      image: aquasec/trivy:latest
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: trivy-cache
          mountPath: /tmp
